name = "g3nproject"
main = "worker.js"
compatibility_date = "2026-10-01"
workers_dev = true

[vars]
SOCIA_VERIFY_MODE = "sbwhook-r8ka2auhtsqjdkgnxwmzp7ty"

[[d1_databases]]
binding = "DB"
database_name = "project-roblox"
database_id = "62e75441-29d8-4997-a58d-8fa40a69a2df"
